### ISSUE TITLE
댓글 에디터를 textarea 로 지정할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by Laeng** [xpressengine/plugin-comment#58]
몇달전에 댓글 에디터로 ckeditor 대신 textarea 로 사용할 수 있었습니다만,
이제는 textarea 로 지정할 수 없게되었습니다. 

댓글 에디터를 지정할 수 있도록 해주시면 대단히 감사드립니다.

**Comment by bnu** [comment]
![xe3](https://user-images.githubusercontent.com/53764/46130806-23a86200-c275-11e8-8600-cd4a2783f59f.png)
게시판 상세 설정 페이지에서 '댓글' 항목의 설정 링크에서 변경할 수 있습니다.

XE3 RC5 및 관련 플러그인의 최신 배포본에서 동작 확인했으나, 별도의 문제가 있으시면 상세 정보 부탁드립니다.
