### ISSUE TITLE
코멘트 에러메세지 발생 뒤 자바스크립트 이벤트 멈춤

### ISSUE THREAD

**Issue by mAKEkr** [xpressengine/plugin-comment#65]
- XE 코어 버전 : 3.0.0
- 브라우저 : Firefox 64, Chrome 70.0.3538.110
- 서버 환경 : XE 체험하기 서버

컨텐츠 없이 전송 하면 axios라이브러리에 인해 Unhandled promise rejection 발생 뒤 그 뒤부터 파일첨부, 모두 먹통이 됩니다.

공홈에서도 구현되는지는 아이디가 휴면처리되어있는 상황이라 확인이 안되네요.

**Comment by bnu** [comment]
감사합니다. 해당 문제 수정했습니다.

https://github.com/xpressengine/plugin-comment/commit/8ed650f66892626ef6f3407e58653c245fa2a2eb#diff-62b4ae935d73f54ec8bc2c3ed71aaf52R764

우선 적용이 필요하다면 `catch` 블럭의 코드를 추가하여 해결할 수 있습니다.
